chores(tooling): enable noUnusedLocals and strict (#112)
* chore(tooling): enable noUnusedLocals

* Chore(linting): fix unreachable locals considered unused

This is the new way for catching unsued variable or imports.
It used to be something handle on tslint level but the [`no-unused-variable`](https://palantir.github.io/tslint/rules/no-unused-variable/) rule has been deprecated since tslint@5.11.0: see https://github.com/palantir/tslint/blob/master/CHANGELOG.md#warning-deprecations.

* chore(tooling): enable strict mode

I had to opt-out of the following settings:

** noImplicitThis **

Adopting this one requires (at least) changes in every method.
At the moment, the main class AlgoliaAnalytics is split accross multiples files. Each method has is own file, more or less.

```ts
// in _sendEvent.ts
function sendEvent(params: any) {
    // reference to `this` is implicit
}

// in insights.ts
class AlgoliaAnalytics {
    protected _sendEvent;

    constructor() {
    	this._sendEvent = sendEvent.bind(this)
    }
}
```

If we want to enable noImplicitThis, we need to use a slightly different pattern

```ts
// in _sendEvent.ts
function sendEvent(this: AlgoliaAnalytics, params: any) {
    // reference to `this` is implicit
}

// in insights.ts
class AlgoliaAnalytics {
    protected _sendEvent;

    constructor() {
    	this._sendEvent = sendEvent.bind(this)
    }
}
```

More on that here: https://www.typescriptlang.org/docs/handbook/functions.html#this-parameters

:warning: There might be other changes required to enable this option. This is the most obvious one.

** strictNullChecks **

This is another one that will require various changes.
The errors raised when enabled are things like.

```
lib/insights.ts:67:3 - error TS2564: Property '_userToken' has no initializer and is not definitely assigned in the constructor.
   _userToken: string;
     ~~~~~~~~~~
```

```
lib/_sendEvent.ts:85:9 - error TS2532: Object is possibly 'undefined'.
     if (eventData.objectIDs.length !== eventData.positions.length) {
```

The first kind can be fixed by passing `this` parameter I think.
The second kind require to ~stop using `isUndefined` helper~ add type type-guards to `isUndefined` helper, as it turns out the first of the following code snippet will throw and error and then second will not.

```ts
    if (isUndefined(eventData.objectIDs)) throw new Error(‘...’)
    return eventData.objectIDs.length;
```
```ts
    if (typeof eventData.objectIDs === 'undefined’) throw new Error(‘...’)
    return eventData.objectIDs.length;
```

* fix: remove unecessary comments

Co-Authored-By: tkrugg <tkrugg@users.noreply.github.com>